name: 'eu_football_dbt'
version: '1.0.0'
config-version: 2

profile: 'dbt'

model-paths: ["models"]
seed-paths:  ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  eu_football_dbt:
    staging:
      +materialized: view
      +schema: eu_football_staging    

    mart:
      +materialized: table
      +schema: eu_football_mart       

seeds:
  eu_football_dbt:
    leagues:
      +schema: eu_football_raw        
      +column_types:
        code:        string
        country:     string
        league_name: string